---
title: Map Visualization
subtitle: Ayush Noori
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
# knitr::opts_chunk$set(message=FALSE, warning=FALSE)
```

# Dependencies

Load requisite packages and define directories.

```{r load-packages, message=FALSE, warning=FALSE}

# data manipulation
library(data.table)
library(purrr)
library(magrittr)

# data visualization
library(ggplot2)

# utility functions
library(brainstorm)

```

Note that directories are relative to the R project path.

```{r define-directores}

# set directories
ddir = file.path("Data")
rdir = file.path("Results", "1 - Map Visualization")

```

# Read Data

Read COVID data.

```{r read-data}

# read data
dat = fread(file.path(ddir, "covid-variants.csv"))

# process data
dat = dat %>%
  .[is.na(num_sequences), num_sequences := 0]

# retrieve map data
world_map = as.data.table(map_data("world"))

# recode names
# unique(dat[!(location %in% world_map$region), .(location)])
dat %>%
  .[, location := dplyr::recode(
    location,
    'United Kingdom' = 'UK',
    'United States' = 'USA',
    'Czechia' = 'Czech Republic',
    'Trinidad and Tobago' = 'Trinidad')]

# get unique columns
unique_date = unique(dat[, .(location, date, num_sequences_total)])
mean_date = dat[, mean(num_sequences_total), by = location] %>%
  setnames("V1", "mean_sequences")


```

# Plot Data

Plot data using `ggplot2`.

```{r plot-data}

# join with original
join_world = merge(world_map, mean_date, by.x = "region", by.y = "location",
                   all.x = T, all.y = F)

# plot data
p = ggplot(join_world, aes(long, lat, group = group)) +
  geom_polygon(aes(fill = mean_sequences), colour = "white") +
  scale_fill_gradientn(colors = c("#264653", "#2a9d8f", "#e9c46a", "#f4a261", "#e76f51")) +
  # scale_fill_viridis_c() +
  theme_classic() +
  labs(fill = "Mean Sequence Count") +
  theme(axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        legend.title = element_text(face = "bold"),
        plot.margin = margin(0, 0, 0, 0))

# save data
ggsave(file.path(rdir, "Map Visualization.pdf"), p, width = 18, height = 10)
ggsave(file.path(rdir, "Map Visualization.png"), p, width = 18, height = 10,
       dpi = 600)

```
